package update

import (
	"os"
	"testing"
)

func TestManifestSignVerify(t *testing.T) {
	// Load the private key generated by tools/genkey
	keyData, err := os.ReadFile("../../update_private_key.pem")
	if err != nil {
		t.Skip("update_private_key.pem not found; run 'go run ./tools/genkey/' first")
	}

	privateKey, err := PEMDecodePrivateKey(keyData)
	if err != nil {
		t.Fatalf("decode private key: %v", err)
	}

	// Load the embedded public key
	publicKey, err := ParsePublicKey()
	if err != nil {
		t.Fatalf("parse public key: %v", err)
	}

	// Create a manifest
	m := &Manifest{
		Version:      "0.1.0-test",
		RulesVersion: 42,
		CreatedAt:    "2026-06-24T00:00:00Z",
		Files: []ManifestFile{
			{Path: "rules/rules.yaml", SHA256: "testchecksum", Size: 123},
		},
	}

	// Sign
	if err := m.Sign(privateKey); err != nil {
		t.Fatalf("sign: %v", err)
	}

	if m.Signature == "" {
		t.Fatal("signature should not be empty")
	}

	// Verify
	if err := m.Verify(publicKey); err != nil {
		t.Fatalf("verify: %v", err)
	}

	// Tamper with the manifest and verify it fails
	m.RulesVersion = 99
	if err := m.Verify(publicKey); err == nil {
		t.Fatal("expected verification failure after tampering")
	}
}

func TestGenerateAndVerifyRoundTrip(t *testing.T) {
	// Generate fresh keys
	priv, pub, err := GenerateKey()
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	m := &Manifest{
		Version:      "1.0.0",
		RulesVersion: 1,
		CreatedAt:    "2026-06-24T12:00:00Z",
		Files: []ManifestFile{
			{Path: "test.yaml", SHA256: "abc123", Size: 100},
		},
	}

	if err := m.Sign(priv); err != nil {
		t.Fatalf("sign: %v", err)
	}

	// Marshal and unmarshal (JSON round-trip)
	data, err := m.Marshal()
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	m2, err := UnmarshalManifest(data)
	if err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if err := m2.Verify(pub); err != nil {
		t.Fatalf("verify after round-trip: %v", err)
	}
}
