package update

// PublicKeyPEM is the embedded Ed25519 public key for verifying signed manifests.
// Generated by elencho gen-key. Replace with your own key for production.
const PublicKeyPEM = "-----BEGIN ED25519 PUBLIC KEY-----\nHcSflxoiLnoXtre0EVIWE1P1/00YLujlxBtv65mgr5M=\n-----END ED25519 PUBLIC KEY-----\n"
