package main

import (
	"fmt"
	"os"

	"github.com/lukemcqueen/elencho/internal/update"
)

func main() {
	priv, pub, err := update.GenerateKey()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("update_private_key.pem", update.PEMEncodePrivateKey(priv), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "write private: %v\n", err)
		os.Exit(1)
	}
	pubPEM := update.PEMEncodePublicKey(pub)
	if err := os.WriteFile("internal/update/public_key.go",
		[]byte(fmt.Sprintf(`package update

// PublicKeyPEM is the embedded Ed25519 public key for verifying signed manifests.
// Generated by elencho gen-key. Replace with your own key for production.
const PublicKeyPEM = %q
`, string(pubPEM))), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write public: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Keys generated:")
	fmt.Printf("  Private: update_private_key.pem\n")
	fmt.Printf("  Public:  internal/update/public_key.go\n")
}
